language: node_js
node_js:
- 6
- 8
- 10
matrix:
  fast_finish: true
cache:
  directories:
  - $HOME/.npm
notifications:
  email: false
  slack:
    secure: 1DPSOqpJqi39ZJvrUOmpjIDLd4vMyg5uBOCH437PN7XMRrfI3E24EH7zt9tYYZZti1EkuFoh4XxH0TQCyUiKBJIH5glqoh1YZG+RLkAODFBKl9PrfM+wpx4lE2htcFz1lr4Cx3hnXXtColYY3v7xo9dvxuE355XwxijZaDZBVY/WoshWof91CKZVC629d/S2JV0IFgTic7bsBlS4UKLPk/h8aqyDy/4gxCD26mLs60fKCCHOL0pH76sf5TukKk+sTmr62WmhcN44EI0SkmTok3sg6NAx4nS8e4ZNqSVUaBWTfqpY9/e1hC0S5bFreLbdZsEDv6tV3tf5vLgfj5GjRWo709b4Rv53I2LPismEgQ4+ctfW715abs2nXRj8CUQR37KHPe+Pcc8tbom2WWTnC06417SfPLIHMJzxcCBNL0h0cQgMwCcoSttS8hCvPdeacviiv7A02cQMjVETMuvWXop1L80spbxcNOhgiUNwZqF07xhHDjOUbZyo8mFjqpw34wd+hte8oQNEiB7XNVzoUnpYY0h9Wtg+LaRd8jSvUeEmtc17u9TrxnvpWcPMBsaBzia2QQ+ovbVwBMb831ihhtUNnDEnus51VT4nBGvECHD49/j7iWhVdwIxm/MTn+DibjweELzzHjjUMyQRW1/lBcNx2T4ojDQMipTny3bfeQE=
